apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: http

---

# $ kubectl exec -it deploy/nginx-deployment -- bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  # 修改配置文件后需要重新部署nginx-deployment： delete + create
  nginx.conf: |
    events {}
    http {
      upstream backend {
        server server;
      }
      server {
        listen 80;
        location / {
          return 200 "hello world\n";
        }
        location /proxy {
          proxy_pass http://backend/;
        }
      }
    }

